//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualBingo.UI.Player.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualBingo.UI.Player.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added questions.
        /// </summary>
        public static string CREATE_GAME_AddedQuestions {
            get {
                return ResourceManager.GetString("CREATE_GAME_AddedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string CREATE_GAME_AddQuestion {
            get {
                return ResourceManager.GetString("CREATE_GAME_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer: .
        /// </summary>
        public static string CREATE_GAME_Answer {
            get {
                return ResourceManager.GetString("CREATE_GAME_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer image: .
        /// </summary>
        public static string CREATE_GAME_AnswerImage {
            get {
                return ResourceManager.GetString("CREATE_GAME_AnswerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game author.
        /// </summary>
        public static string CREATE_GAME_AuthorOfTheGame {
            get {
                return ResourceManager.GetString("CREATE_GAME_AuthorOfTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD QUESTION.
        /// </summary>
        public static string CREATE_GAME_CAPS_AddQuestion {
            get {
                return ResourceManager.GetString("CREATE_GAME_CAPS_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE GAME.
        /// </summary>
        public static string CREATE_GAME_CAPS_SaveGame {
            get {
                return ResourceManager.GetString("CREATE_GAME_CAPS_SaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this if the image is necessary to understand the question.
        /// </summary>
        public static string CREATE_GAME_CheckIfNecessary {
            get {
                return ResourceManager.GetString("CREATE_GAME_CheckIfNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert at least a title or title image and an answer or answer image.
        /// </summary>
        public static string CREATE_GAME_ErrorAddingQuestion {
            get {
                return ResourceManager.GetString("CREATE_GAME_ErrorAddingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CREATE_GAME_ErrorCreatingGame {
            get {
                return ResourceManager.GetString("CREATE_GAME_ErrorCreatingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image required: .
        /// </summary>
        public static string CREATE_GAME_ImageRequired {
            get {
                return ResourceManager.GetString("CREATE_GAME_ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of the game.
        /// </summary>
        public static string CREATE_GAME_LanguageOfTheGame {
            get {
                return ResourceManager.GetString("CREATE_GAME_LanguageOfTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject of the game.
        /// </summary>
        public static string CREATE_GAME_SubjectOfTheGame {
            get {
                return ResourceManager.GetString("CREATE_GAME_SubjectOfTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: .
        /// </summary>
        public static string CREATE_GAME_Title {
            get {
                return ResourceManager.GetString("CREATE_GAME_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title image: .
        /// </summary>
        public static string CREATE_GAME_TitleImage {
            get {
                return ResourceManager.GetString("CREATE_GAME_TitleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic of the game.
        /// </summary>
        public static string CREATE_GAME_TopicOfTheGame {
            get {
                return ResourceManager.GetString("CREATE_GAME_TopicOfTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of cards.
        /// </summary>
        public static string GENERATE_CARDS_AmountOfCards {
            get {
                return ResourceManager.GetString("GENERATE_CARDS_AmountOfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of questions per card.
        /// </summary>
        public static string GENERATE_CARDS_AmountOfQuestionsPerCard {
            get {
                return ResourceManager.GetString("GENERATE_CARDS_AmountOfQuestionsPerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while trying to load the select game.
        ///
        ///To copy more information about the error and get help, use the copy to clipboard button..
        /// </summary>
        public static string GENERATE_CARDS_ErrorLoadingGame {
            get {
                return ResourceManager.GetString("GENERATE_CARDS_ErrorLoadingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate cards for the selected game.
        /// </summary>
        public static string GENERATE_CARDS_GenerateSelectedGame {
            get {
                return ResourceManager.GetString("GENERATE_CARDS_GenerateSelectedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cards were generated successfully!.
        /// </summary>
        public static string GENERATE_CARDS_SuccessGenerating {
            get {
                return ResourceManager.GetString("GENERATE_CARDS_SuccessGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GENERIC_Cancel {
            get {
                return ResourceManager.GetString("GENERIC_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GENERIC_Error {
            get {
                return ResourceManager.GetString("GENERIC_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while trying to load the select game..
        /// </summary>
        public static string GENERIC_ErrorLoadingGame {
            get {
                return ResourceManager.GetString("GENERIC_ErrorLoadingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill all necessary fields before continuing!.
        /// </summary>
        public static string GENERIC_FillNecessaryFields {
            get {
                return ResourceManager.GetString("GENERIC_FillNecessaryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string GENERIC_Ok {
            get {
                return ResourceManager.GetString("GENERIC_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question answer.
        /// </summary>
        public static string GENERIC_QuestionAnswer {
            get {
                return ResourceManager.GetString("GENERIC_QuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question answer image path.
        /// </summary>
        public static string GENERIC_QuestionAnswerImagePath {
            get {
                return ResourceManager.GetString("GENERIC_QuestionAnswerImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title.
        /// </summary>
        public static string GENERIC_QuestionTitle {
            get {
                return ResourceManager.GetString("GENERIC_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title image path.
        /// </summary>
        public static string GENERIC_QuestionTitleImagePath {
            get {
                return ResourceManager.GetString("GENERIC_QuestionTitleImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string GENERIC_Success {
            get {
                return ResourceManager.GetString("GENERIC_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This part of the application is under construction and should be avaliable soon..
        /// </summary>
        public static string GENERIC_UnderConstruction {
            get {
                return ResourceManager.GetString("GENERIC_UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE GAME.
        /// </summary>
        public static string HEADER_CreateGame {
            get {
                return ResourceManager.GetString("HEADER_CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLORE.
        /// </summary>
        public static string HEADER_Explore {
            get {
                return ResourceManager.GetString("HEADER_Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME#.
        /// </summary>
        public static string HEADER_Game {
            get {
                return ResourceManager.GetString("HEADER_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATE CARDS.
        /// </summary>
        public static string HEADER_GenerateCards {
            get {
                return ResourceManager.GetString("HEADER_GenerateCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string HEADER_Help {
            get {
                return ResourceManager.GetString("HEADER_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIRTUAL BINGO.
        /// </summary>
        public static string HEADER_Menu {
            get {
                return ResourceManager.GetString("HEADER_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string HEADER_Play {
            get {
                return ResourceManager.GetString("HEADER_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string HEADER_Settings {
            get {
                return ResourceManager.GetString("HEADER_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown version.
        /// </summary>
        public static string MAIN_UnknownVersion {
            get {
                return ResourceManager.GetString("MAIN_UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create game.
        /// </summary>
        public static string MENU_CreateGame {
            get {
                return ResourceManager.GetString("MENU_CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new game.
        /// </summary>
        public static string MENU_CreateGameMessage {
            get {
                return ResourceManager.GetString("MENU_CreateGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string MENU_Explore {
            get {
                return ResourceManager.GetString("MENU_Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOON.
        /// </summary>
        public static string MENU_ExploreMessage {
            get {
                return ResourceManager.GetString("MENU_ExploreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate cards.
        /// </summary>
        public static string MENU_GenerateCards {
            get {
                return ResourceManager.GetString("MENU_GenerateCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate cards for an existing game.
        /// </summary>
        public static string MENU_GenerateCardsMessage {
            get {
                return ResourceManager.GetString("MENU_GenerateCardsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MENU_Help {
            get {
                return ResourceManager.GetString("MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help for this application.
        /// </summary>
        public static string MENU_HelpMessage {
            get {
                return ResourceManager.GetString("MENU_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string MENU_Play {
            get {
                return ResourceManager.GetString("MENU_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new game.
        /// </summary>
        public static string MENU_PlayMessage {
            get {
                return ResourceManager.GetString("MENU_PlayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MENU_Settings {
            get {
                return ResourceManager.GetString("MENU_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application settings.
        /// </summary>
        public static string MENU_SettingsMessage {
            get {
                return ResourceManager.GetString("MENU_SettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT QUESTION.
        /// </summary>
        public static string PLAY_CurrentQuestion {
            get {
                return ResourceManager.GetString("PLAY_CurrentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End game and return.
        /// </summary>
        public static string PLAY_EndGame {
            get {
                return ResourceManager.GetString("PLAY_EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to enable the &apos;Narrate Question Title&apos; setting.
        /// </summary>
        public static string PLAY_Mute {
            get {
                return ResourceManager.GetString("PLAY_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next question.
        /// </summary>
        public static string PLAY_NextQuestionTooltip {
            get {
                return ResourceManager.GetString("PLAY_NextQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open answers window for this game.
        /// </summary>
        public static string PLAY_OpenAnswersWindow {
            get {
                return ResourceManager.GetString("PLAY_OpenAnswersWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIOUS QUESTION.
        /// </summary>
        public static string PLAY_PreviousQuestion {
            get {
                return ResourceManager.GetString("PLAY_PreviousQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous question.
        /// </summary>
        public static string PLAY_PreviousQuestionTooltip {
            get {
                return ResourceManager.GetString("PLAY_PreviousQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to disable the &apos;Narrate Question Title&apos; setting.
        /// </summary>
        public static string PLAY_Unmute {
            get {
                return ResourceManager.GetString("PLAY_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliable games.
        /// </summary>
        public static string START_GAME_AvaliableGames {
            get {
                return ResourceManager.GetString("START_GAME_AvaliableGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter options.
        /// </summary>
        public static string START_GAME_FilterOptions {
            get {
                return ResourceManager.GetString("START_GAME_FilterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string START_GAME_Language {
            get {
                return ResourceManager.GetString("START_GAME_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload avaliable games and filter options.
        /// </summary>
        public static string START_GAME_ReloadAvaliable {
            get {
                return ResourceManager.GetString("START_GAME_ReloadAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start selected game.
        /// </summary>
        public static string START_GAME_StartSelectedGame {
            get {
                return ResourceManager.GetString("START_GAME_StartSelectedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string START_GAME_Subject {
            get {
                return ResourceManager.GetString("START_GAME_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic:.
        /// </summary>
        public static string START_GAME_Topic {
            get {
                return ResourceManager.GetString("START_GAME_Topic", resourceCulture);
            }
        }
    }
}
